### ISSUE TITLE
How to send additional information along with a notification?

### ISSUE THREAD

**Issue by derwaldgeist** [raix/push#167]
Both APN and GCM allow the server to send arbitrary data along with the core message. In APN, you can do this by sending an additional dictionary besides the "apn" standard dictionary, and in GCM you can add a data payload. In APN, you can also use the "content-available" flag to receive "silent" notifications without bringing the app to the foreground.

Are this additional options supported by ```raix:push``` somehow?

**Comment by raix** [comment]
yes, we support ejson payload - so it's formatted correctly on both android and ios (ios tends to flatten payloads)

regarding content-available - it has been discussed - not sure if it's supported in the latest cordova plugin.

*I haven't added it to the push package, mainly because it's limited to once a day usage.*

**Comment by derwaldgeist** [comment]
Thanks for the info. How exactly can the payload be added?

**Comment by raix** [comment]
https://github.com/raix/push#common-api
Push.send({ /* ... */ payload: { foo: 'bar' } });

**Comment by derwaldgeist** [comment]
Thanks!
